version: '3'
services:
  web:
    build: .
    ports:
      - "$PORT:3000"
    volumes:
      - data:/app/data
volumes:
  data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=10.0.2.4,rw"
      device: /stack-test-data
